// @generated by the MaaS generation adapter (backlog #547) — Web-Fetch HTTP shell.
// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;
// regenerate with `npm run gen:maas-origin`. Deterministic: same IR in, byte-identical out.
//
// The IR specifies the wire contract — URL grammar, cache policy, status table, header vocabulary. It
// deliberately does NOT specify content-hash IDENTITY, definition RESOLUTION, or the TRANSFORM; those are
// INJECTED here, exactly as the JS reference origin (fetchHandler.ts) injects resolve/resolver. This keeps
// the shell framework-free: it runs anywhere the Web Fetch API (Request/Response/URL) exists.
import { BASE_PATH, CACHE_POLICY, HEADERS, STATUS, MEDIA_TYPES, isHashPin } from './origin.core.js';

const jsonError = (status, message) =>
  new Response(JSON.stringify({ error: message }), {
    status,
    headers: { 'Content-Type': MEDIA_TYPES.error },
  });

/**
 * Build a deterministic, framework-agnostic MaaS origin: (Request) => Promise<Response>.
 * Inject the non-IR-derivable seams:
 *   - identity(definition, result, params, producer) => { id, integrity }  (content-hash, #088 §1/§3)
 *   - resolveDefinition(name) => string | null                            (definition registry)
 *   - transform(definition, params) => { code, language }                 (the served-form transform)
 */
export function createGeneratedMaaSOrigin(deps) {
  const { identity, resolveDefinition, transform } = deps;
  const producer = deps.producer ?? 'webadapters/0.0.0';
  const basePath = deps.basePath ?? BASE_PATH;

  return async function handle(request) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith(basePath))
      return jsonError(STATUS.notFound, `Not a MaaS request (expected ${basePath}<name>.js).`);

    let spec = decodeURIComponent(url.pathname.slice(basePath.length)).replace(/\.js$/, '');
    if (!spec) return jsonError(STATUS.notFound, 'Empty component spec.');
    const at = spec.lastIndexOf('@');
    const name = at >= 0 ? spec.slice(0, at) : spec;
    const pin = at >= 0 ? spec.slice(at + 1) : null;
    if (!name) return jsonError(STATUS.notFound, 'Missing component name.');

    const form = url.searchParams.get('form') ?? undefined;
    const target = url.searchParams.get('target') ?? undefined;
    const strategy = url.searchParams.get('strategy') ?? undefined;

    const definition = resolveDefinition(name);
    if (definition == null) return jsonError(STATUS.notFound, `No component "${name}".`);

    let result;
    try {
      result = await transform(definition, { form, target, strategy });
    } catch (e) {
      return jsonError(STATUS.serverError, `serve failed: ${e.message}`);
    }

    const id = await identity(definition, result, { form, target, strategy }, producer);

    const baseHeaders = () => {
      const h = new Headers();
      h.set(HEADERS.producer, producer);
      if (result.lossy) h.set(HEADERS.lossy, '1');
      if (result.diagnostics && result.diagnostics.length)
        h.set(HEADERS.diagnostic, encodeURIComponent(result.diagnostics.join(' | ')));
      return h;
    };

    // A floating tag / exact semver redirects (short-TTL) to the terminal content-hash URL (#088 §2).
    if (!isHashPin(pin)) {
      const h = baseHeaders();
      h.set('Location', `${basePath}${encodeURIComponent(name)}@${id.id}.js${url.search}`);
      h.set('Cache-Control', CACHE_POLICY.floating);
      return new Response(null, { status: STATUS.redirect, headers: h });
    }

    // Terminal content-hash pin that doesn't match current state — this origin serves only current bytes.
    if (pin !== id.id)
      return jsonError(STATUS.notFound, `No artifact "${name}@${pin}" — current id is ${id.id}.`);

    const etag = `"${id.id}"`;
    if (request.headers.get('If-None-Match') === etag) {
      const h = baseHeaders();
      h.set('ETag', etag);
      h.set('Cache-Control', CACHE_POLICY.immutable);
      return new Response(null, { status: STATUS.notModified, headers: h });
    }

    const h = baseHeaders();
    h.set('Content-Type', MEDIA_TYPES.javascript);
    h.set('Cache-Control', CACHE_POLICY.immutable);
    h.set('ETag', etag);
    h.set(HEADERS.integrity, id.integrity);
    return new Response(result.code, { status: STATUS.ok, headers: h });
  };
}
