// @generated by the MaaS generation adapter (backlog #547) — language-neutral serve-path core.
// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;
// regenerate with `npm run gen:maas-origin`. Deterministic: same IR in, byte-identical out.

export const VERSION = '1.0.0';
export const HASH_ALGORITHM = 'sha256';
export const HASH_PIN_PATTERN = '^sha256-[A-Za-z0-9_-]+$';
export const BASE_PATH = '/_maas/';
export const ROUTE = '<name>[@<pin>].js';
export const METHOD = 'GET';

export const CACHE_POLICY = {
  immutable: 'public, max-age=31536000, immutable',
  floating: 'public, max-age=60, must-revalidate',
};

export const HEADERS = {
  producer: 'X-MaaS-Producer',
  lossy: 'X-MaaS-Lossy',
  diagnostic: 'X-MaaS-Diagnostic',
  integrity: 'X-MaaS-Integrity',
};

export const STATUS = {
  ok: 200,
  redirect: 302,
  notModified: 304,
  badRequest: 400,
  notFound: 404,
  serverError: 500,
};

export const MEDIA_TYPES = {
  javascript: 'text/javascript; charset=utf-8',
  html: 'text/html; charset=utf-8',
  error: 'application/json; charset=utf-8',
};

export const PARAMS = [
  { name: 'form', required: false, catalogGated: true, description: 'The served form (e.g. wc-class). Defaults to the origin\'s default form. The value set is an implementation catalog, not part of the neutral contract.' },
  { name: 'target', required: false, description: 'The transpile target passed to the transform (e.g. an ES version). Byte-determining.' },
  { name: 'strategy', required: false, description: 'The define/delivery strategy passed to the transform. Byte-determining.' },
];

export const RESPONSES = [
  { status: 200, when: 'A terminal content-hash pin matching the current artifact id.', headers: ['Content-Type', 'Cache-Control', 'ETag', 'X-MaaS-Integrity', 'X-MaaS-Producer'], mediaType: 'text/javascript; charset=utf-8' },
  { status: 302, when: 'A floating tag or exact semver — redirected to the terminal content-hash URL.', headers: ['Location', 'Cache-Control', 'X-MaaS-Producer'], mediaType: null },
  { status: 304, when: 'A hash-pinned request whose If-None-Match equals the current ETag.', headers: ['ETag', 'Cache-Control', 'X-MaaS-Producer'], mediaType: null },
  { status: 400, when: 'An unknown form query value.', headers: [], mediaType: 'application/json; charset=utf-8' },
  { status: 404, when: 'No such component, a non-MaaS path, or a hash pin that does not match current state.', headers: [], mediaType: 'application/json; charset=utf-8' },
  { status: 500, when: 'The injected transform threw.', headers: [], mediaType: 'application/json; charset=utf-8' },
];

/** A pin that is itself a terminal content hash — served immutable, never redirected (#088 §2). */
export const isHashPin = (pin) => pin != null && new RegExp(HASH_PIN_PATTERN).test(pin);
