/**
 * @file blocks/renderers/module-service/generation/backends/csharp.ts
 * @description The .NET / C# backend for the generation adapter (backlog #548, slice 2 of #507) — the
 * first FOREIGN native target, proving the slice-1 ({@link file://./javascript.ts}) {@link LanguageBackend}
 * interface generalizes past JavaScript.
 *
 * Like the JS backend, it is a pure, deterministic projection of the neutral serve-path IR
 * ({@link file://../../servePathIR.ts}): same IR in, byte-identical C# out, NO AI in the path (#463 fork
 * a). It emits the same deterministic-core / HTTP-shell split, rendered idiomatically for .NET — the core
 * is a `static class` of `const`/`readonly` fields; the shell is a framework-agnostic handler over plain
 * request/response POCOs (no ASP.NET dependency) with the IR's injection seams (identity, definition
 * resolution, transform) supplied as delegates, exactly as the JS shell injects them.
 *
 * Scope (per #548): the runtime is AI-free pure-native and Wasm is out of scope. EXECUTION conformance —
 * compiling the emitted C# and running it through the #506 suite — is slice 3 (#549); this slice locks
 * the generated source byte-for-byte (the drift gate) and proves the backend interface is language-neutral.
 */
import {
  HTTP_STATUS,
  MEDIA_TYPES,
  type ServePathIR,
  type ServePathParam,
  type ServePathResponse,
} from '../../servePathIR';
import type { GeneratedOrigin, LanguageBackend } from '../languageBackend';

// ── Deterministic C# literal emit ──────────────────────────────────────────────────

/** A C# double-quoted string literal with `\`, `"`, and newline escaping. */
const cs = (s: string): string =>
  `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;

/** PascalCase a camelCase IR key (`notModified` → `NotModified`) for an idiomatic C# member name. */
const pascal = (k: string): string => k.charAt(0).toUpperCase() + k.slice(1);

/** A C# string-array literal: `new[] { "a", "b" }` (or `System.Array.Empty<string>()` when empty). */
const strArray = (xs: readonly string[]): string =>
  xs.length === 0 ? 'System.Array.Empty<string>()' : `new[] { ${xs.map(cs).join(', ')} }`;

const constBlock = (name: string, entries: [string, string][]): string =>
  `    public static class ${name}\n    {\n` +
  entries.map(([k, v]) => `        public const ${v.startsWith('"') ? 'string' : 'int'} ${pascal(k)} = ${v};`).join('\n') +
  '\n    }';

const emitParam = (p: ServePathParam): string =>
  `        new ServePathParam(${cs(p.name)}, ${p.required}, ${cs(p.description)}),`;

const emitResponse = (r: ServePathResponse): string =>
  `        new ServePathResponse(${r.status}, ${cs(r.when)}, ${strArray(r.headers)}, ${
    r.mediaType === null ? 'null' : cs(r.mediaType)
  }),`;

const GEN_NOTICE = (kind: string): string =>
  `// @generated by the MaaS generation adapter (backlog #548) — ${kind}.\n` +
  `// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;\n` +
  `// regenerate with \`npm run gen:maas-origin\`. Deterministic: same IR in, byte-identical out.`;

const NAMESPACE = 'FrontierUI.Maas.Generated';

/** Emit the language-neutral core as an idiomatic C# `static class`. */
function emitCore(ir: ServePathIR): string {
  const cache = constBlock('CachePolicy', [
    ['immutable', cs(ir.cachePolicy.immutable)],
    ['floating', cs(ir.cachePolicy.floating)],
  ]);
  const headers = constBlock(
    'Headers',
    Object.entries(ir.headers).map(([k, v]) => [k, cs(v)] as [string, string]),
  );
  const status = constBlock(
    'Status',
    Object.entries(HTTP_STATUS).map(([k, v]) => [k, String(v)] as [string, string]),
  );
  const media = constBlock(
    'MediaTypes',
    Object.entries(MEDIA_TYPES).map(([k, v]) => [k, cs(v)] as [string, string]),
  );
  const params = ir.params.map(emitParam).join('\n');
  const responses = ir.responses.map(emitResponse).join('\n');

  return `${GEN_NOTICE('language-neutral serve-path core')}
namespace ${NAMESPACE};

/// <summary>One query parameter of the serve path (name, required, role).</summary>
public readonly record struct ServePathParam(string Name, bool Required, string Description);

/// <summary>One response the serve path can produce, tied to its HTTP status.</summary>
public readonly record struct ServePathResponse(int Status, string When, string[] Headers, string? MediaType);

/// <summary>The neutral MaaS serve-path contract, rendered from servePathIR.ts (#505).</summary>
public static class OriginCore
{
    public const string Version = ${cs(ir.version)};
    public const string HashAlgorithm = ${cs(ir.hashAlgorithm)};
    public const string HashPinPattern = ${cs(ir.hashPinPattern)};
    public const string BasePath = ${cs(ir.basePath)};
    public const string Route = ${cs(ir.route)};
    public const string Method = ${cs(ir.method)};

${cache}

${headers}

${status}

${media}

    public static readonly ServePathParam[] Params = new[]
    {
${params}
    };

    public static readonly ServePathResponse[] Responses = new[]
    {
${responses}
    };

    /// <summary>A pin that is itself a terminal content hash — served immutable, never redirected (#088 §2).</summary>
    public static bool IsHashPin(string? pin) =>
        pin != null && System.Text.RegularExpressions.Regex.IsMatch(pin, HashPinPattern);
}
`;
}

/** Emit the idiomatic .NET HTTP shell — a framework-agnostic handler with the IR's injection seams. */
function emitShell(ir: ServePathIR): string {
  const paramReads = ir.params
    .map(
      (p) =>
        `        var ${p.name} = query.TryGetValue(${cs(p.name)}, out var _${p.name}) ? _${p.name} : null;`,
    )
    .join('\n');
  const paramDict =
    '            new Dictionary<string, string?>\n            {\n' +
    ir.params.map((p) => `                [${cs(p.name)}] = ${p.name},`).join('\n') +
    '\n            }';

  return `${GEN_NOTICE('framework-agnostic HTTP shell')}
//
// The IR specifies the wire contract — URL grammar, cache policy, status table, header vocabulary. It
// deliberately does NOT specify content-hash IDENTITY, definition RESOLUTION, or the TRANSFORM; those are
// INJECTED here as delegates, exactly as the JS reference origin (fetchHandler.ts) injects resolve/resolver.
// Plain POCOs in/out so the handler has no ASP.NET dependency (host it under any .NET HTTP stack).
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ${NAMESPACE};

public sealed record OriginRequest(string Url, IReadOnlyDictionary<string, string> Headers);

public sealed class OriginResponse
{
    public int Status { get; init; }
    public string? Body { get; init; }
    public Dictionary<string, string> Headers { get; } = new();
}

/// <summary>The transform's result: served bytes + language + diagnostics (#081).</summary>
public sealed record TransformResult(string Code, string Language, bool Lossy, IReadOnlyList<string> Diagnostics);

/// <summary>Content-addressed identity for a served artifact (#088 §1/§3).</summary>
public sealed record ArtifactIdentity(string Id, string Integrity);

/// <summary>A deterministic, framework-agnostic MaaS origin built from injected seams.</summary>
public sealed class GeneratedMaaSOrigin
{
    private readonly Func<string, string?> _resolveDefinition;
    private readonly Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<TransformResult>> _transform;
    private readonly Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<ArtifactIdentity>> _identity;
    private readonly string _producer;
    private readonly string _basePath;

    public GeneratedMaaSOrigin(
        Func<string, string?> resolveDefinition,
        Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<TransformResult>> transform,
        Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<ArtifactIdentity>> identity,
        string producer = "webadapters/0.0.0",
        string? basePath = null)
    {
        _resolveDefinition = resolveDefinition;
        _transform = transform;
        _identity = identity;
        _producer = producer;
        _basePath = basePath ?? OriginCore.BasePath;
    }

    private static OriginResponse JsonError(int status, string message) => new()
    {
        Status = status,
        Body = "{\\"error\\":" + System.Text.Json.JsonSerializer.Serialize(message) + "}",
        Headers = { ["Content-Type"] = OriginCore.MediaTypes.Error },
    };

    public async Task<OriginResponse> HandleAsync(OriginRequest request)
    {
        var uri = new Uri(request.Url);
        if (!uri.AbsolutePath.StartsWith(_basePath, StringComparison.Ordinal))
            return JsonError(OriginCore.Status.NotFound, $"Not a MaaS request (expected {_basePath}<name>.js).");

        var spec = Uri.UnescapeDataString(uri.AbsolutePath.Substring(_basePath.Length));
        if (spec.EndsWith(".js", StringComparison.Ordinal)) spec = spec[..^3];
        if (spec.Length == 0) return JsonError(OriginCore.Status.NotFound, "Empty component spec.");
        var at = spec.LastIndexOf('@');
        var name = at >= 0 ? spec[..at] : spec;
        var pin = at >= 0 ? spec[(at + 1)..] : null;
        if (name.Length == 0) return JsonError(OriginCore.Status.NotFound, "Missing component name.");

        var query = System.Web.HttpUtility.ParseQueryString(uri.Query);
${paramReads}

        var definition = _resolveDefinition(name);
        if (definition == null) return JsonError(OriginCore.Status.NotFound, $"No component \\"{name}\\".");

        var paramMap = (IReadOnlyDictionary<string, string?>)
${paramDict};

        TransformResult result;
        try { result = await _transform(definition, default!, paramMap, _producer); }
        catch (Exception e) { return JsonError(OriginCore.Status.ServerError, $"serve failed: {e.Message}"); }

        var id = await _identity(definition, result, paramMap, _producer);

        void Base(OriginResponse r)
        {
            r.Headers[OriginCore.Headers.Producer] = _producer;
            if (result.Lossy) r.Headers[OriginCore.Headers.Lossy] = "1";
            if (result.Diagnostics is { Count: > 0 })
                r.Headers[OriginCore.Headers.Diagnostic] = Uri.EscapeDataString(string.Join(" | ", result.Diagnostics));
        }

        // A floating tag / exact semver redirects (short-TTL) to the terminal content-hash URL (#088 §2).
        if (!OriginCore.IsHashPin(pin))
        {
            var r = new OriginResponse { Status = OriginCore.Status.Redirect };
            Base(r);
            r.Headers["Location"] = $"{_basePath}{Uri.EscapeDataString(name)}@{id.Id}.js{uri.Query}";
            r.Headers["Cache-Control"] = OriginCore.CachePolicy.Floating;
            return r;
        }

        if (pin != id.Id)
            return JsonError(OriginCore.Status.NotFound, $"No artifact \\"{name}@{pin}\\" — current id is {id.Id}.");

        var etag = $"\\"{id.Id}\\"";
        if (request.Headers.TryGetValue("If-None-Match", out var inm) && inm == etag)
        {
            var r = new OriginResponse { Status = OriginCore.Status.NotModified };
            Base(r);
            r.Headers["ETag"] = etag;
            r.Headers["Cache-Control"] = OriginCore.CachePolicy.Immutable;
            return r;
        }

        var ok = new OriginResponse { Status = OriginCore.Status.Ok, Body = result.Code };
        Base(ok);
        ok.Headers["Content-Type"] = OriginCore.MediaTypes.Javascript;
        ok.Headers["Cache-Control"] = OriginCore.CachePolicy.Immutable;
        ok.Headers["ETag"] = etag;
        ok.Headers[OriginCore.Headers.Integrity] = id.Integrity;
        return ok;
    }
}
`;
}

/** The C# / .NET generation backend — emits a `{ core, shell }` origin from the neutral IR. */
export const csharpBackend: LanguageBackend = {
  id: 'csharp',
  emit(ir: ServePathIR): GeneratedOrigin {
    return {
      backend: 'csharp',
      core: { filename: 'OriginCore.cs', language: 'csharp', source: emitCore(ir) },
      shell: { filename: 'GeneratedMaaSOrigin.cs', language: 'csharp', source: emitShell(ir) },
    };
  },
};
