/**
 * @file blocks/renderers/module-service/generation/backends/javascript.ts
 * @description The JavaScript proof backend for the generation adapter (backlog #547, slice 1 of #507).
 *
 * The first {@link LanguageBackend}, and the one that validates the interface before any foreign target:
 * it regenerates an idiomatic JS MaaS origin from the neutral serve-path IR
 * ({@link file://../../servePathIR.ts}), and the committed golden ({@link
 * file://../../../../../../scripts/gen-maas-origin.mjs}) is locked byte-for-byte by a drift test. JS is
 * the deliberate first target because the JS reference origin ({@link file://../../fetchHandler.ts}) is
 * already covered by the #506 conformance suite — so generating JS proves the core/shell split and the
 * backend contract against an *already-conformant* language before #548 takes on .NET.
 *
 * Determinism (the #463 fork-a invariant): every value emitted here is a pure function of the IR (or of
 * the IR module's frozen constant maps), serialized in the IR's own fixed key/element order. No clock, no
 * randomness — the engine ({@link file://../generate.ts}) enforces this by emitting twice and comparing.
 */
import {
  HTTP_STATUS,
  MEDIA_TYPES,
  type ServePathIR,
  type ServePathParam,
  type ServePathResponse,
} from '../../servePathIR';
import type { GeneratedOrigin, LanguageBackend } from '../languageBackend';

// ── Deterministic JS literal emit ──────────────────────────────────────────────────
// Small, dependency-free serializers. Object keys follow insertion order (the IR's frozen order), so
// output is stable. Strings are single-quoted with the minimal escaping prettier would produce.

/** A single-quoted JS string literal with `\`, `'`, and newline escaping. */
const q = (s: string): string =>
  `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

/** A JS array literal of strings on one line: `['a', 'b']`. */
const strArray = (xs: readonly string[]): string => `[${xs.map(q).join(', ')}]`;

const emitParam = (p: ServePathParam): string =>
  `{ name: ${q(p.name)}, required: ${p.required}, description: ${q(p.description)} }`;

const emitResponse = (r: ServePathResponse): string =>
  `{ status: ${r.status}, when: ${q(r.when)}, headers: ${strArray(r.headers)}, mediaType: ${
    r.mediaType === null ? 'null' : q(r.mediaType)
  } }`;

const GEN_NOTICE = (kind: string): string =>
  `// @generated by the MaaS generation adapter (backlog #547) — ${kind}.\n` +
  `// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;\n` +
  `// regenerate with \`npm run gen:maas-origin\`. Deterministic: same IR in, byte-identical out.`;

/** Emit the language-neutral core module: the IR's byte-determining contract as idiomatic JS constants. */
function emitCore(ir: ServePathIR): string {
  const cachePolicy =
    `{\n  immutable: ${q(ir.cachePolicy.immutable)},\n  floating: ${q(ir.cachePolicy.floating)},\n}`;
  const headers =
    '{\n' +
    Object.entries(ir.headers)
      .map(([k, v]) => `  ${k}: ${q(v)},`)
      .join('\n') +
    '\n}';
  const status =
    '{\n' +
    Object.entries(HTTP_STATUS)
      .map(([k, v]) => `  ${k}: ${v},`)
      .join('\n') +
    '\n}';
  const media =
    '{\n' +
    Object.entries(MEDIA_TYPES)
      .map(([k, v]) => `  ${k}: ${q(v)},`)
      .join('\n') +
    '\n}';
  const params = '[\n' + ir.params.map((p) => `  ${emitParam(p)},`).join('\n') + '\n]';
  const responses = '[\n' + ir.responses.map((r) => `  ${emitResponse(r)},`).join('\n') + '\n]';

  return (
    `${GEN_NOTICE('language-neutral serve-path core')}\n\n` +
    `export const VERSION = ${q(ir.version)};\n` +
    `export const HASH_ALGORITHM = ${q(ir.hashAlgorithm)};\n` +
    `export const HASH_PIN_PATTERN = ${q(ir.hashPinPattern)};\n` +
    `export const BASE_PATH = ${q(ir.basePath)};\n` +
    `export const ROUTE = ${q(ir.route)};\n` +
    `export const METHOD = ${q(ir.method)};\n\n` +
    `export const CACHE_POLICY = ${cachePolicy};\n\n` +
    `export const HEADERS = ${headers};\n\n` +
    `export const STATUS = ${status};\n\n` +
    `export const MEDIA_TYPES = ${media};\n\n` +
    `export const PARAMS = ${params};\n\n` +
    `export const RESPONSES = ${responses};\n\n` +
    `/** A pin that is itself a terminal content hash — served immutable, never redirected (#088 §2). */\n` +
    `export const isHashPin = (pin) => pin != null && new RegExp(HASH_PIN_PATTERN).test(pin);\n`
  );
}

/** Emit the idiomatic HTTP shell: a Web-Fetch handler wiring the core, with the IR's injection seams. */
function emitShell(ir: ServePathIR): string {
  // Query extraction is IR-derived: one line per declared param, in IR order.
  const paramReads = ir.params
    .map((p) => `    const ${p.name} = url.searchParams.get(${q(p.name)}) ?? undefined;`)
    .join('\n');
  const paramPass = ir.params.map((p) => `${p.name}`).join(', ');

  return `${GEN_NOTICE('Web-Fetch HTTP shell')}
//
// The IR specifies the wire contract — URL grammar, cache policy, status table, header vocabulary. It
// deliberately does NOT specify content-hash IDENTITY, definition RESOLUTION, or the TRANSFORM; those are
// INJECTED here, exactly as the JS reference origin (fetchHandler.ts) injects resolve/resolver. This keeps
// the shell framework-free: it runs anywhere the Web Fetch API (Request/Response/URL) exists.
import { BASE_PATH, CACHE_POLICY, HEADERS, STATUS, MEDIA_TYPES, isHashPin } from './origin.core.js';

const jsonError = (status, message) =>
  new Response(JSON.stringify({ error: message }), {
    status,
    headers: { 'Content-Type': MEDIA_TYPES.error },
  });

/**
 * Build a deterministic, framework-agnostic MaaS origin: (Request) => Promise<Response>.
 * Inject the non-IR-derivable seams:
 *   - identity(definition, result, params, producer) => { id, integrity }  (content-hash, #088 §1/§3)
 *   - resolveDefinition(name) => string | null                            (definition registry)
 *   - transform(definition, params) => { code, language }                 (the served-form transform)
 */
export function createGeneratedMaaSOrigin(deps) {
  const { identity, resolveDefinition, transform } = deps;
  const producer = deps.producer ?? 'webadapters/0.0.0';
  const basePath = deps.basePath ?? BASE_PATH;

  return async function handle(request) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith(basePath))
      return jsonError(STATUS.notFound, \`Not a MaaS request (expected \${basePath}<name>.js).\`);

    let spec = decodeURIComponent(url.pathname.slice(basePath.length)).replace(/\\.js$/, '');
    if (!spec) return jsonError(STATUS.notFound, 'Empty component spec.');
    const at = spec.lastIndexOf('@');
    const name = at >= 0 ? spec.slice(0, at) : spec;
    const pin = at >= 0 ? spec.slice(at + 1) : null;
    if (!name) return jsonError(STATUS.notFound, 'Missing component name.');

${paramReads}

    const definition = resolveDefinition(name);
    if (definition == null) return jsonError(STATUS.notFound, \`No component "\${name}".\`);

    let result;
    try {
      result = await transform(definition, { ${paramPass} });
    } catch (e) {
      return jsonError(STATUS.serverError, \`serve failed: \${e.message}\`);
    }

    const id = await identity(definition, result, { ${paramPass} }, producer);

    const baseHeaders = () => {
      const h = new Headers();
      h.set(HEADERS.producer, producer);
      if (result.lossy) h.set(HEADERS.lossy, '1');
      if (result.diagnostics && result.diagnostics.length)
        h.set(HEADERS.diagnostic, encodeURIComponent(result.diagnostics.join(' | ')));
      return h;
    };

    // A floating tag / exact semver redirects (short-TTL) to the terminal content-hash URL (#088 §2).
    if (!isHashPin(pin)) {
      const h = baseHeaders();
      h.set('Location', \`\${basePath}\${encodeURIComponent(name)}@\${id.id}.js\${url.search}\`);
      h.set('Cache-Control', CACHE_POLICY.floating);
      return new Response(null, { status: STATUS.redirect, headers: h });
    }

    // Terminal content-hash pin that doesn't match current state — this origin serves only current bytes.
    if (pin !== id.id)
      return jsonError(STATUS.notFound, \`No artifact "\${name}@\${pin}" — current id is \${id.id}.\`);

    const etag = \`"\${id.id}"\`;
    if (request.headers.get('If-None-Match') === etag) {
      const h = baseHeaders();
      h.set('ETag', etag);
      h.set('Cache-Control', CACHE_POLICY.immutable);
      return new Response(null, { status: STATUS.notModified, headers: h });
    }

    const h = baseHeaders();
    h.set('Content-Type', MEDIA_TYPES.javascript);
    h.set('Cache-Control', CACHE_POLICY.immutable);
    h.set('ETag', etag);
    h.set(HEADERS.integrity, id.integrity);
    return new Response(result.code, { status: STATUS.ok, headers: h });
  };
}
`;
}

/** The JavaScript generation backend — emits a `{ core, shell }` origin from the neutral IR. */
export const javascriptBackend: LanguageBackend = {
  id: 'javascript',
  emit(ir: ServePathIR): GeneratedOrigin {
    return {
      backend: 'javascript',
      core: { filename: 'origin.core.js', language: 'javascript', source: emitCore(ir) },
      shell: { filename: 'origin.shell.js', language: 'javascript', source: emitShell(ir) },
    };
  },
};
