// @generated by the MaaS generation adapter (backlog #548) — framework-agnostic HTTP shell.
// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;
// regenerate with `npm run gen:maas-origin`. Deterministic: same IR in, byte-identical out.
//
// The IR specifies the wire contract — URL grammar, cache policy, status table, header vocabulary. It
// deliberately does NOT specify content-hash IDENTITY, definition RESOLUTION, or the TRANSFORM; those are
// INJECTED here as delegates, exactly as the JS reference origin (fetchHandler.ts) injects resolve/resolver.
// Plain POCOs in/out so the handler has no ASP.NET dependency (host it under any .NET HTTP stack).
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FrontierUI.Maas.Generated;

public sealed record OriginRequest(string Url, IReadOnlyDictionary<string, string> Headers);

public sealed class OriginResponse
{
    public int Status { get; init; }
    public string? Body { get; init; }
    public Dictionary<string, string> Headers { get; } = new();
}

/// <summary>The transform's result: served bytes + language + diagnostics (#081).</summary>
public sealed record TransformResult(string Code, string Language, bool Lossy, IReadOnlyList<string> Diagnostics);

/// <summary>Content-addressed identity for a served artifact (#088 §1/§3).</summary>
public sealed record ArtifactIdentity(string Id, string Integrity);

/// <summary>A deterministic, framework-agnostic MaaS origin built from injected seams.</summary>
public sealed class GeneratedMaaSOrigin
{
    private readonly Func<string, string?> _resolveDefinition;
    private readonly Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<TransformResult>> _transform;
    private readonly Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<ArtifactIdentity>> _identity;
    private readonly string _producer;
    private readonly string _basePath;

    public GeneratedMaaSOrigin(
        Func<string, string?> resolveDefinition,
        Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<TransformResult>> transform,
        Func<string, TransformResult, IReadOnlyDictionary<string, string?>, string, Task<ArtifactIdentity>> identity,
        string producer = "webadapters/0.0.0",
        string? basePath = null)
    {
        _resolveDefinition = resolveDefinition;
        _transform = transform;
        _identity = identity;
        _producer = producer;
        _basePath = basePath ?? OriginCore.BasePath;
    }

    private static OriginResponse JsonError(int status, string message) => new()
    {
        Status = status,
        Body = "{\"error\":" + System.Text.Json.JsonSerializer.Serialize(message) + "}",
        Headers = { ["Content-Type"] = OriginCore.MediaTypes.Error },
    };

    public async Task<OriginResponse> HandleAsync(OriginRequest request)
    {
        var uri = new Uri(request.Url);
        if (!uri.AbsolutePath.StartsWith(_basePath, StringComparison.Ordinal))
            return JsonError(OriginCore.Status.NotFound, $"Not a MaaS request (expected {_basePath}<name>.js).");

        var spec = Uri.UnescapeDataString(uri.AbsolutePath.Substring(_basePath.Length));
        if (spec.EndsWith(".js", StringComparison.Ordinal)) spec = spec[..^3];
        if (spec.Length == 0) return JsonError(OriginCore.Status.NotFound, "Empty component spec.");
        var at = spec.LastIndexOf('@');
        var name = at >= 0 ? spec[..at] : spec;
        var pin = at >= 0 ? spec[(at + 1)..] : null;
        if (name.Length == 0) return JsonError(OriginCore.Status.NotFound, "Missing component name.");

        var query = System.Web.HttpUtility.ParseQueryString(uri.Query);
        var form = query["form"];
        var target = query["target"];
        var strategy = query["strategy"];

        var definition = _resolveDefinition(name);
        if (definition == null) return JsonError(OriginCore.Status.NotFound, $"No component \"{name}\".");

        var paramMap = (IReadOnlyDictionary<string, string?>)
            new Dictionary<string, string?>
            {
                ["form"] = form,
                ["target"] = target,
                ["strategy"] = strategy,
            };

        TransformResult result;
        try { result = await _transform(definition, default!, paramMap, _producer); }
        catch (Exception e) { return JsonError(OriginCore.Status.ServerError, $"serve failed: {e.Message}"); }

        var id = await _identity(definition, result, paramMap, _producer);

        void Base(OriginResponse r)
        {
            r.Headers[OriginCore.Headers.Producer] = _producer;
            if (result.Lossy) r.Headers[OriginCore.Headers.Lossy] = "1";
            if (result.Diagnostics is { Count: > 0 })
                r.Headers[OriginCore.Headers.Diagnostic] = Uri.EscapeDataString(string.Join(" | ", result.Diagnostics));
        }

        // A floating tag / exact semver redirects (short-TTL) to the terminal content-hash URL (#088 §2).
        if (!OriginCore.IsHashPin(pin))
        {
            var r = new OriginResponse { Status = OriginCore.Status.Redirect };
            Base(r);
            r.Headers["Location"] = $"{_basePath}{Uri.EscapeDataString(name)}@{id.Id}.js{uri.Query}";
            r.Headers["Cache-Control"] = OriginCore.CachePolicy.Floating;
            return r;
        }

        if (pin != id.Id)
            return JsonError(OriginCore.Status.NotFound, $"No artifact \"{name}@{pin}\" — current id is {id.Id}.");

        var etag = $"\"{id.Id}\"";
        if (request.Headers.TryGetValue("If-None-Match", out var inm) && inm == etag)
        {
            var r = new OriginResponse { Status = OriginCore.Status.NotModified };
            Base(r);
            r.Headers["ETag"] = etag;
            r.Headers["Cache-Control"] = OriginCore.CachePolicy.Immutable;
            return r;
        }

        var ok = new OriginResponse { Status = OriginCore.Status.Ok, Body = result.Code };
        Base(ok);
        ok.Headers["Content-Type"] = OriginCore.MediaTypes.Javascript;
        ok.Headers["Cache-Control"] = OriginCore.CachePolicy.Immutable;
        ok.Headers["ETag"] = etag;
        ok.Headers[OriginCore.Headers.Integrity] = id.Integrity;
        return ok;
    }
}
