// @generated by the MaaS generation adapter (backlog #548) — language-neutral serve-path core.
// Source of truth: the neutral serve-path IR (servePathIR.ts, #505). DO NOT EDIT BY HAND;
// regenerate with `npm run gen:maas-origin`. Deterministic: same IR in, byte-identical out.
namespace FrontierUI.Maas.Generated;

/// <summary>One query parameter of the serve path (name, required, role).</summary>
public readonly record struct ServePathParam(string Name, bool Required, bool CatalogGated, string Description);

/// <summary>One response the serve path can produce, tied to its HTTP status.</summary>
public readonly record struct ServePathResponse(int Status, string When, string[] Headers, string? MediaType);

/// <summary>The neutral MaaS serve-path contract, rendered from servePathIR.ts (#505).</summary>
public static class OriginCore
{
    public const string Version = "1.0.0";
    public const string HashAlgorithm = "sha256";
    public const string HashPinPattern = "^sha256-[A-Za-z0-9_-]+$";
    public const string BasePath = "/_maas/";
    public const string Route = "<name>[@<pin>].js";
    public const string Method = "GET";

    public static class CachePolicy
    {
        public const string Immutable = "public, max-age=31536000, immutable";
        public const string Floating = "public, max-age=60, must-revalidate";
    }

    public static class Headers
    {
        public const string Producer = "X-MaaS-Producer";
        public const string Lossy = "X-MaaS-Lossy";
        public const string Diagnostic = "X-MaaS-Diagnostic";
        public const string Integrity = "X-MaaS-Integrity";
    }

    public static class Status
    {
        public const int Ok = 200;
        public const int Redirect = 302;
        public const int NotModified = 304;
        public const int BadRequest = 400;
        public const int NotFound = 404;
        public const int ServerError = 500;
    }

    public static class MediaTypes
    {
        public const string Javascript = "text/javascript; charset=utf-8";
        public const string Html = "text/html; charset=utf-8";
        public const string Error = "application/json; charset=utf-8";
    }

    public static readonly ServePathParam[] Params = new[]
    {
        new ServePathParam("form", false, true, "The served form (e.g. wc-class). Defaults to the origin's default form. The value set is an implementation catalog, not part of the neutral contract."),
        new ServePathParam("target", false, false, "The transpile target passed to the transform (e.g. an ES version). Byte-determining."),
        new ServePathParam("strategy", false, false, "The define/delivery strategy passed to the transform. Byte-determining."),
    };

    public static readonly ServePathResponse[] Responses = new[]
    {
        new ServePathResponse(200, "A terminal content-hash pin matching the current artifact id.", new[] { "Content-Type", "Cache-Control", "ETag", "X-MaaS-Integrity", "X-MaaS-Producer" }, "text/javascript; charset=utf-8"),
        new ServePathResponse(302, "A floating tag or exact semver — redirected to the terminal content-hash URL.", new[] { "Location", "Cache-Control", "X-MaaS-Producer" }, null),
        new ServePathResponse(304, "A hash-pinned request whose If-None-Match equals the current ETag.", new[] { "ETag", "Cache-Control", "X-MaaS-Producer" }, null),
        new ServePathResponse(400, "An unknown form query value.", System.Array.Empty<string>(), "application/json; charset=utf-8"),
        new ServePathResponse(404, "No such component, a non-MaaS path, or a hash pin that does not match current state.", System.Array.Empty<string>(), "application/json; charset=utf-8"),
        new ServePathResponse(500, "The injected transform threw.", System.Array.Empty<string>(), "application/json; charset=utf-8"),
    };

    /// <summary>A pin that is itself a terminal content hash — served immutable, never redirected (#088 §2).</summary>
    public static bool IsHashPin(string? pin) =>
        pin != null && System.Text.RegularExpressions.Regex.IsMatch(pin, HashPinPattern);
}
