/**
 * @file blocks/renderers/module-service/generation/corpus/snapshot.ts
 * @description The snapshot gate for the regression corpus (backlog #551). Runs every backend over every
 * {@link CORPUS} fixture through the deterministic engine and flattens the result to a stable, diffable map
 * of `"<fixture>/<backend>/<core|shell filename>" -> source`. The committed snapshot
 * ({@link file://./__snapshots__}) is regenerated by `npm run gen:maas-origin` and asserted equal by a
 * drift test — so editing a backend's templates shows up as a reviewable snapshot diff across all inputs.
 */
import { generateOrigin } from '../generate';
import type { LanguageBackend } from '../languageBackend';
import { CORPUS } from './fixtures';

/** A flat, stable map of snapshot key → emitted source. Keys sort deterministically. */
export type CorpusSnapshot = Record<string, string>;

/** Run all `backends` over all corpus fixtures; return the flattened snapshot map. */
export function runCorpus(backends: readonly LanguageBackend[]): CorpusSnapshot {
  const out: CorpusSnapshot = {};
  for (const fixture of CORPUS) {
    for (const backend of backends) {
      const origin = generateOrigin(backend, fixture.ir);
      out[`${fixture.name}/${backend.id}/${origin.core.filename}`] = origin.core.source;
      out[`${fixture.name}/${backend.id}/${origin.shell.filename}`] = origin.shell.source;
    }
  }
  return out;
}

/** Serialize a snapshot to a stable, pretty JSON string (sorted keys) with a trailing newline. */
export function serializeSnapshot(snapshot: CorpusSnapshot): string {
  const sorted: CorpusSnapshot = {};
  for (const k of Object.keys(snapshot).sort()) sorted[k] = snapshot[k];
  return `${JSON.stringify(sorted, null, 2)}\n`;
}
