/**
 * Shared mapping fixtures for the JSX Adapter — the single source of truth for the HTML↔JSX
 * mirror-dialect example pairs.
 *
 * Imported by BOTH the JSX Adapter Playground demo (demos/jsx-adapter-demo.tsx) and the
 * unit/conformance suites (blocks/__tests__/unit/renderers/*). Editing a case here updates the
 * demo's live cards AND the tests at once, so the demo's green badges can never silently drift
 * from CI. See reports/2026-06-03-jsx-adapter-feature-mapping.md.
 *
 * The JSX factory is auto-injected by esbuild (`jsxInject` in vite.config.mts and vitest.config.ts),
 * so JSX is written directly here and compiles to `jsx.createElement` in both the browser and vitest.
 */

// Declared for editor/type tooling; the actual binding is injected by esbuild.
declare const jsx: typeof import('/blocks/renderers/jsx').default;

export interface MappingCase {
  /** Stable id (kebab) for keying parallel structures and test labels. */
  id: string;
  title: string;
  note?: string;
  /** The authored JSX source, shown verbatim as text (the JSX compiles away). */
  jsx: string;
  /** Live render through the realigned renderer — kept in lockstep with `jsx`. */
  render: () => Node;
  /** The canonical HTML this JSX must produce (the mapping contract). */
  html: string;
  /** This JSX has no faithful HTML representation (e.g. a function handler), so it cannot round-trip. */
  lossy?: boolean;
}

export const mappingCases: MappingCase[] = [
  {
    id: 'element-class-text',
    title: '1 · Element, class, text',
    note: 'class — never className. Plain element + text round-trips as identity.',
    jsx: `<div class="card">Hello</div>`,
    render: () => <div class="card">Hello</div>,
    html: `<div class="card">Hello</div>`,
  },
  {
    id: 'attrs-boolean-data-bind',
    title: '2 · Attributes — boolean, data, hyphenated binding',
    note: 'Bare boolean, data-*, and bind-* (the Axis-1 reversible binding form) all become plain attributes.',
    jsx: `<input type="text" required data-id="42" bind-text="count" />`,
    render: () => <input type="text" required data-id="42" bind-text="count" />,
    html: `<input type="text" required data-id="42" bind-text="count">`,
  },
  {
    id: 'events-fn-vs-string',
    title: '3 · Events — function prop vs string behavior',
    note: 'onclick={fn} wires a real listener (try it) and leaves no HTML trace; on:select="..." stays a string behavior attribute.',
    jsx:
      `<button class="btn"\n` +
      `        onclick={(e) => (e.currentTarget.textContent = 'Clicked ✓')}\n` +
      `        on:select="choose($event)">Click me</button>`,
    render: () => (
      <button
        class="btn"
        onclick={(e: Event) => ((e.currentTarget as HTMLElement).textContent = 'Clicked ✓')}
        on:select="choose($event)"
      >
        Click me
      </button>
    ),
    // the function handler is a listener, not an attribute — so it does not appear in the HTML,
    // and therefore cannot be regenerated by htmlToJsx (the documented lossy case, mapping row 5)
    html: `<button class="btn" on:select="choose($event)">Click me</button>`,
    lossy: true,
  },
  {
    id: 'classname-htmlfor-aliases',
    title: '4 · className / htmlFor aliases lower to class / for',
    note: 'React-style sources keep working: className → class, htmlFor → for. The produced HTML is the canonical mirror.',
    jsx: `<label className="lbl" htmlFor="email">Email</label>`,
    render: () => <label className="lbl" htmlFor="email">Email</label>,
    html: `<label class="lbl" for="email">Email</label>`,
  },
  {
    id: 'context-ref',
    title: '5 · Context reference (injector alias)',
    note: 'Injector/context refs are plain string attributes — identity across formats.',
    jsx: `<drop-list options="@countries" placeholder="Country"></drop-list>`,
    render: () => <drop-list options="@countries" placeholder="Country"></drop-list>,
    html: `<drop-list options="@countries" placeholder="Country"></drop-list>`,
  },
  {
    id: 'fragment',
    title: '6 · Fragment — multiple roots',
    note: 'A <>…</> fragment maps to sibling nodes with no wrapper (DocumentFragment at runtime).',
    jsx: `<>\n  <li>Argentina</li>\n  <li>Australia</li>\n</>`,
    render: () => (
      <>
        <li>Argentina</li>
        <li>Australia</li>
      </>
    ),
    html: `<li>Argentina</li><li>Australia</li>`,
  },
  {
    id: 'slots',
    title: '7 · Slots / content projection',
    note: 'Named slots are the slot attribute, identical in both formats.',
    jsx: `<user-card>\n  <span slot="title">Ada Lovelace</span>\n  <p>First programmer.</p>\n</user-card>`,
    render: () => (
      <user-card>
        <span slot="title">Ada Lovelace</span>
        <p>First programmer.</p>
      </user-card>
    ),
    html: `<user-card><span slot="title">Ada Lovelace</span><p>First programmer.</p></user-card>`,
  },
  {
    id: 'directive-for-each',
    title: '8 · Directive — customized built-in via is',
    note: 'The JSX mirror of <!-- control:for-each -->: createElement("template", { is: "for-each" }); children land in .content.',
    jsx:
      `<template is="for-each" items="users" key="id">\n` +
      `  <div class="user-row"><span data-bind="name"></span></div>\n` +
      `</template>`,
    render: () => (
      <template is="for-each" items="users" key="id">
        <div class="user-row">
          <span data-bind="name"></span>
        </div>
      </template>
    ),
    html: `<template is="for-each" items="users" key="id"><div class="user-row"><span data-bind="name"></span></div></template>`,
  },
];

export default mappingCases;

/**
 * Lenient JSX equivalence — the relation that DEFINES "round-trips" for the mirror dialect.
 * Two JSX sources are equivalent if they differ only in formatting, fragment wrappers, the
 * className/htmlFor aliases, and `<x/>` vs `<x></x>`. Shared by the demo and the test suites so
 * "does htmlToJsx reproduce the authored JSX?" means the same thing everywhere.
 */
export function jsxEquivalent(a: string, b: string): boolean {
  const n = (s: string) =>
    s
      .replace(/<>|<\/>/g, '') // drop fragment wrappers
      .replace(/\bclassName=/g, 'class=') // aliases are equivalent in the mirror dialect
      .replace(/\bhtmlFor=/g, 'for=')
      .replace(/\s*\/>/g, '>') // <x /> → <x>
      .replace(/<(\w[\w-]*)\b([^>]*)><\/\1>/g, '<$1$2>') // <x a></x> → <x a>
      .replace(/>\s+</g, '><')
      .replace(/\s+/g, ' ')
      .trim();
  return n(a) === n(b);
}
