/**
 * @file scripts/readiness/__tests__/check-standards-scope-replay.test.mjs
 * @description Unit proof of the #4164 replay harness that gates epic #4163. Pure — no git, no child_process,
 *   no real check-standards.mjs run (that lives in the real replay artefact, `check-standards-scope-replay-baseline.json`,
 *   generated by a real CLI invocation and checked in alongside this test).
 */
import { describe, it, expect } from 'vitest';
import {
  isLaneMergeSubject,
  parseMergeLog,
  MERGE_LOG_FORMAT,
  selectLaneDiffs,
  idsForPath,
  linkedFilesFor,
  MAX_LINKED_HITS_PER_ID,
  findingIdentity,
  compareFindings,
  parseBsdTime,
  summarize,
  formatTable,
} from '../check-standards-scope-replay.mjs';

describe('isLaneMergeSubject', () => {
  it('matches the drain merge shape', () => {
    expect(isLaneMergeSubject('Merge pull request #2653 from chalbert/lane/xvzc4v4-drain-merge-safety')).toBe(true);
  });
  it('rejects a non-lane merge and non-merge subjects', () => {
    expect(isLaneMergeSubject('Merge pull request #12 from chalbert/hotfix-thing')).toBe(false);
    expect(isLaneMergeSubject('drain: resolve #4177 on land (#2748)')).toBe(false);
    expect(isLaneMergeSubject('')).toBe(false);
    expect(isLaneMergeSubject(undefined)).toBe(false);
  });
});

describe('parseMergeLog', () => {
  it('splits sha / parents / subject on the unit-separator format', () => {
    const sep = '\x1f';
    const text = [
      `aaa${sep}bbb ccc${sep}Merge pull request #1 from x/lane/y`,
      `ddd${sep}eee fff${sep}some | subject with pipes`,
    ].join('\n');
    expect(parseMergeLog(text)).toEqual([
      { sha: 'aaa', parents: ['bbb', 'ccc'], subject: 'Merge pull request #1 from x/lane/y' },
      { sha: 'ddd', parents: ['eee', 'fff'], subject: 'some | subject with pipes' },
    ]);
  });
  it('ignores blank lines and rows with no sha', () => {
    expect(parseMergeLog('\n\n')).toEqual([]);
  });
  it('MERGE_LOG_FORMAT uses the unit-separator, not a pipe', () => {
    expect(MERGE_LOG_FORMAT).not.toContain('|');
    expect(MERGE_LOG_FORMAT.split('\x1f')).toHaveLength(3);
  });
});

describe('selectLaneDiffs', () => {
  const rows = [
    { sha: 'm1', parents: ['b1', 'h1'], subject: 'Merge pull request #1 from x/lane/a' },
    { sha: 'm2', parents: ['b2'], subject: 'Merge pull request #2 from x/lane/b' }, // not 2-parent — skipped
    { sha: 'm3', parents: ['b3', 'h3'], subject: 'Merge pull request #3 from x/hotfix-c' }, // not a lane merge
    { sha: 'm4', parents: ['b4', 'h4'], subject: 'Merge pull request #4 from x/lane/d' }, // empty diff — skipped
    { sha: 'm5', parents: ['b5', 'h5'], subject: 'Merge pull request #5 from x/lane/e' },
  ];
  function fakeGit(base) {
    return (args) => {
      if (args[0] === 'merge-base') return `mb-${args[1]}-${args[2]}`;
      if (args[0] === 'diff') {
        const head = args[3];
        if (head === 'h4') return '';
        return `src/${head}.mjs\ndocs/${head}.md`;
      }
      throw new Error(`unexpected: ${args.join(' ')}`);
    };
  }

  it('keeps only 2-parent lane merges with a non-empty diff, up to count', () => {
    const out = selectLaneDiffs({ rows, runGit: fakeGit(), count: 50 });
    expect(out.map((d) => d.sha)).toEqual(['m1', 'm5']);
    expect(out[0]).toEqual({
      sha: 'm1', subject: rows[0].subject, base: 'b1', head: 'h1', mergeBase: 'mb-b1-h1',
      changedFiles: ['docs/h1.md', 'src/h1.mjs'],
    });
  });

  it('stops at count even if more candidates remain', () => {
    const out = selectLaneDiffs({ rows, runGit: fakeGit(), count: 1 });
    expect(out).toHaveLength(1);
    expect(out[0].sha).toBe('m1');
  });

  it('offset skips that many otherwise-valid diffs before collecting count (batched replay support)', () => {
    const out = selectLaneDiffs({ rows, runGit: fakeGit(), count: 1, offset: 1 });
    expect(out.map((d) => d.sha)).toEqual(['m5']);
  });

  it('skips a candidate whose git commands throw (unreachable sha)', () => {
    const throwing = (args) => { if (args[0] === 'merge-base' && args[1] === 'b5') throw new Error('bad object'); return fakeGit()(args); };
    const out = selectLaneDiffs({ rows, runGit: throwing, count: 50 });
    expect(out.map((d) => d.sha)).toEqual(['m1']);
  });
});

describe('idsForPath', () => {
  it('extracts a specific stem', () => {
    expect(idsForPath('docs/agent/check-standards-thing.md')).toEqual(['check-standards-thing']);
  });
  it('drops generic/short stems', () => {
    expect(idsForPath('src/index.ts')).toEqual([]);
    expect(idsForPath('a/b/id.mjs')).toEqual([]);
  });
  it('adds the bare and hash-prefixed numeric id for a backlog file', () => {
    expect(idsForPath('backlog/4164-check-standards-scoped-mode-replay-proof.md')).toEqual(
      expect.arrayContaining(['4164', '#4164', '4164-check-standards-scoped-mode-replay-proof']),
    );
  });
});

describe('linkedFilesFor', () => {
  it('unions git-grep hits for every changed file\'s ids, excluding the changed files themselves', () => {
    const hits = { '4164': ['docs/agent/epic-notes.md', 'backlog/4164-check-standards-scoped-mode-replay-proof.md'] };
    const gitGrep = (needle) => hits[needle] || [];
    const out = linkedFilesFor(['backlog/4164-check-standards-scoped-mode-replay-proof.md'], { gitGrep });
    expect(out).toEqual(['docs/agent/epic-notes.md']);
  });
  it('returns [] when nothing references any changed id', () => {
    expect(linkedFilesFor(['src/index.ts'], { gitGrep: () => [] })).toEqual([]);
  });

  it('drops an id whose hit count exceeds MAX_LINKED_HITS_PER_ID — too common to be a real link (#4164 live finding)', () => {
    const tooCommon = Array.from({ length: MAX_LINKED_HITS_PER_ID + 1 }, (_, i) => `file${i}.md`);
    const gitGrep = (needle) => (needle === 'common-word' ? tooCommon : ['real-link.md']);
    const out = linkedFilesFor(['scripts/common-word.mjs'], { gitGrep });
    expect(out).toEqual([]);
  });

  it('keeps an id at or under the cap', () => {
    const atCap = Array.from({ length: MAX_LINKED_HITS_PER_ID }, (_, i) => `file${i}.md`);
    const gitGrep = () => atCap;
    const out = linkedFilesFor(['scripts/thing.mjs'], { gitGrep });
    expect(out).toHaveLength(MAX_LINKED_HITS_PER_ID);
  });
});

describe('findingIdentity + compareFindings', () => {
  const f = (message, descriptor) => ({ message, descriptor });

  it('two findings with the same kind/file/message are the same identity', () => {
    const a = f('bad thing', { kind: 'x', file: 'a.md' });
    const b = f('bad thing', { kind: 'x', file: 'a.md' });
    expect(findingIdentity(a)).toBe(findingIdentity(b));
  });

  it('MISSES a full-mode finding on a lane file that scoped mode dropped', () => {
    const fullErrors = [
      f('citation missing', { kind: 'dangling-ref', file: 'docs/agent/linked.md' }), // on a LINKED (not changed) file
      f('typo', { kind: 'typo', file: 'src/changed.mjs' }), // on a changed file, present in both
      f('unrelated', { kind: 'x', file: 'somewhere/else.md' }), // not a lane file — never counted
    ];
    const scopedErrors = [f('typo', { kind: 'typo', file: 'src/changed.mjs' })]; // the linked-file finding is gone
    const { missed, missedCount, laneRelevantCount } = compareFindings({
      fullErrors, scopedErrors, laneFiles: ['src/changed.mjs', 'docs/agent/linked.md'],
    });
    expect(missedCount).toBe(1);
    expect(missed[0].message).toBe('citation missing');
    expect(laneRelevantCount).toBe(2); // the typo + the dangling-ref, not the unrelated one
  });

  it('is a PASS (zero misses) when every lane-relevant full finding survives scoping', () => {
    const fullErrors = [f('typo', { kind: 'typo', file: 'src/changed.mjs' })];
    const scopedErrors = [f('typo', { kind: 'typo', file: 'src/changed.mjs' })];
    const { missedCount } = compareFindings({ fullErrors, scopedErrors, laneFiles: ['src/changed.mjs'] });
    expect(missedCount).toBe(0);
  });

  it('a path-less finding is never counted as lane-relevant (fail-safe scope, not this proof\'s concern)', () => {
    const fullErrors = [f('global dup id', undefined)];
    const { missedCount, laneRelevantCount } = compareFindings({ fullErrors, scopedErrors: [], laneFiles: ['src/changed.mjs'] });
    expect(laneRelevantCount).toBe(0);
    expect(missedCount).toBe(0);
  });
});

describe('parseBsdTime', () => {
  it('parses a real macOS `/usr/bin/time -l` report', () => {
    const text = [
      '        1.23 real         1.10 user         0.13 sys',
      '           123456  maximum resident set size',
      '                0  average shared memory size',
    ].join('\n');
    expect(parseBsdTime(text)).toEqual({ realSec: 1.23, userSec: 1.10, sysSec: 0.13, maxRssBytes: 123456 });
  });
  it('is tolerant of missing/garbled input', () => {
    expect(parseBsdTime('')).toEqual({ realSec: null, userSec: null, sysSec: null, maxRssBytes: null });
    expect(parseBsdTime(undefined)).toEqual({ realSec: null, userSec: null, sysSec: null, maxRssBytes: null });
  });
});

describe('summarize + formatTable', () => {
  const row = (over = {}) => ({
    sha: 'abc1234567', subject: 's', changedCount: 2, linkedCount: 1,
    full: { realSec: 16, userSec: 12, sysSec: 4, errors: 3, warnings: 1 },
    scoped: { realSec: 16, userSec: 12, sysSec: 4, errors: 3, warnings: 1 },
    missedCount: 0, laneRelevantCount: 3, missed: [],
    ...over,
  });

  it('averages timings and reports PASS when nothing was missed', () => {
    const rows = [row(), row()];
    const s = summarize(rows);
    expect(s.pass).toBe(true);
    expect(s.diffCount).toBe(2);
    expect(s.fullRealAvg).toBe(16);
    expect(s.realSavingsPct).toBe(0); // today's baseline: no time saved
  });

  it('FAILs and counts misses when any diff missed a finding', () => {
    const rows = [row(), row({ missedCount: 2 })];
    const s = summarize(rows);
    expect(s.pass).toBe(false);
    expect(s.totalMissed).toBe(2);
    expect(s.diffsWithMisses).toBe(1);
  });

  it('excludes errored rows from the timing averages but counts them', () => {
    const rows = [row(), { sha: 'bad', subject: 's', error: 'boom' }];
    const s = summarize(rows);
    expect(s.okCount).toBe(1);
    expect(s.erroredCount).toBe(1);
    expect(s.diffCount).toBe(2);
  });

  it('formatTable renders one line per row plus a summary footer, and marks an errored row', () => {
    const rows = [row()];
    const s = summarize(rows);
    const table = formatTable(rows, s);
    expect(table).toContain('abc123456');
    expect(table).toContain('PASS');
    const errored = [{ sha: 'deadbeef01', subject: 's', error: 'boom' }];
    const t2 = formatTable(errored, summarize(errored));
    expect(t2).toContain('ERROR: boom');
  });
});
