/**
 * JSX Adapter Playground — mirror-dialect rendering sandbox + conformance harness.
 *
 * Authors each example in the HTML *mirror dialect* of JSX (class not className, for not htmlFor,
 * on:* string behaviors, bind-* bindings, <template is="..."> directives), renders it live through
 * the realigned JSX renderer, shows the produced HTML, and CHECKS it against the canonical HTML the
 * mapping says it must equal (DOM-equality, attribute-order-independent). A red badge means the
 * renderer or the mapping drifted — fix it here before porting pairs onto block pages.
 *
 * See reports/2026-06-03-jsx-adapter-feature-mapping.md. JSX is auto-injected by vite.config.mts.
 */

import { htmlToJsx } from '/blocks/renderers/jsx/htmlToJsx';
import { mappingCases, jsxEquivalent, type MappingCase } from '/blocks/renderers/jsx/__fixtures__/mapping-cases';
import { producedHtml, domEqual, setPlaygroundReady } from '/demos/playground-harness';

// The auto-injected factory, declared for editor/type tooling.
declare const jsx: typeof import('/blocks/renderers/jsx').default;

// The example pairs live in the SHARED fixture module (imported by the unit + conformance suites
// too), so the badges below are backed by CI and can never silently drift from the tests. The
// card/badge/summary + DOM-equality chrome comes from the shared playground-harness.
type Example = MappingCase;
const examples: Example[] = mappingCases;

let passCount = 0;
let roundTripCount = 0;

/** Build one example card. The chrome is itself authored in JSX (dogfooding the renderer). */
function card(ex: Example): Node {
  const live = ex.render();
  const html = producedHtml(live);
  const pass = domEqual(live, ex.html); // render direction: JSX → DOM == canonical
  if (pass) passCount++;

  const generated = htmlToJsx(ex.html); // transform direction: canonical HTML → JSX
  const roundTrips = jsxEquivalent(generated, ex.jsx);
  if (!ex.lossy && roundTrips) roundTripCount++;

  return (
    <section class="ex">
      <h2 class="ex-title">
        {ex.title}
        <span class={`badge ${pass ? 'pass' : 'fail'}`}>{pass ? '✓ conformant' : '✗ drift'}</span>
        {ex.lossy ? (
          <span class="badge info">lossy by design</span>
        ) : (
          <span class={`badge ${roundTrips ? 'pass' : 'fail'}`}>
            {roundTrips ? '✓ round-trips' : '✗ differs'}
          </span>
        )}
      </h2>
      {ex.note ? <p class="ex-note">{ex.note}</p> : null}
      <div class="ex-grid">
        <div class="pane">
          <div class="pane-label">JSX source (authored)</div>
          <pre class="code">{ex.jsx}</pre>
          <div class="pane-label" style="margin-top:0.75rem">Generated by htmlToJsx(HTML)</div>
          <pre class="code gen">{generated}</pre>
        </div>
        <div class="pane">
          <div class="pane-label">Live render</div>
          <div class="preview">{live}</div>
        </div>
        <div class="pane">
          <div class="pane-label">Produced HTML {pass ? '= canonical' : '≠ canonical'}</div>
          <pre class="code">{html}</pre>
        </div>
      </div>
    </section>
  );
}

const host = document.getElementById('examples');
if (host) {
  const cards = examples.map(card);
  const reversible = examples.filter((e) => !e.lossy).length;
  const lossy = examples.length - reversible;
  const allPass = passCount === examples.length && roundTripCount === reversible;
  const summary = (
    <div class={`summary ${allPass ? 'pass' : 'fail'}`}>
      Render: {passCount}/{examples.length} conformant (JSX→DOM = canonical) · Transform:{' '}
      {roundTripCount}/{reversible} round-trip (htmlToJsx → authored JSX){lossy ? `, ${lossy} lossy by design` : ''}
    </div>
  );
  host.replaceChildren(summary, ...cards);
}

// Activate any custom attributes the renderer produced (best-effort; bootstrap may expose `attributes`).
const we = window as unknown as { attributes?: { upgrade?: (root: Node) => void } };
we.attributes?.upgrade?.(document.body);

setPlaygroundReady(passCount);
