/**
 * JSX Adapter Playground — mirror-dialect rendering sandbox + conformance harness.
 *
 * Authors each example in the HTML *mirror dialect* of JSX (class not className, for not htmlFor,
 * on:* string behaviors, bind-* bindings, <template is="..."> directives), renders it live through
 * the realigned JSX renderer, shows the produced HTML, and CHECKS it against the canonical HTML the
 * mapping says it must equal (DOM-equality, attribute-order-independent). A red badge means the
 * renderer or the mapping drifted — fix it here before porting pairs onto block pages.
 *
 * See reports/2026-06-03-jsx-adapter-feature-mapping.md. JSX is auto-injected by vite.config.mts.
 */

import { htmlToJsx } from '/blocks/renderers/jsx/htmlToJsx';
import { jsxToHtml } from '/blocks/renderers/jsx/jsxToHtml';
import type { JsxDialect } from '/blocks/renderers/jsx/dialect';
import { mappingCases, jsxEquivalent, type MappingCase } from '/blocks/renderers/jsx/__fixtures__/mapping-cases';
import { producedHtml, domEqual, setPlaygroundReady } from '/demos/playground-harness';

// The auto-injected factory, declared for editor/type tooling.
declare const jsx: typeof import('/blocks/renderers/jsx').default;

// The example pairs live in the SHARED fixture module (imported by the unit + conformance suites
// too), so the badges below are backed by CI and can never silently drift from the tests. The
// card/badge/summary + DOM-equality chrome comes from the shared playground-harness.
type Example = MappingCase;
const examples: Example[] = mappingCases;

// Authoring dialect (#235): a soft preference governing the spelling the "Generated" pane emits —
// `html` (default) vs `react`. Toggling it re-renders the SAME source in the other dialect; the
// conformance/round-trip badges stay on the canonical `html` dialect (the preference is cosmetic).
let dialect: JsxDialect = 'html';

/** Build one example card. The chrome is itself authored in JSX (dogfooding the renderer). */
function card(ex: Example): { node: Node; pass: boolean; roundTrips: boolean } {
  const live = ex.render();
  const html = producedHtml(live);
  const pass = domEqual(live, ex.html); // render direction: JSX → DOM == canonical

  // Round-trip badge is judged on the canonical (html) dialect; the displayed pane follows the
  // selected dialect. Both ingest back to the same canonical HTML (asserted in jsxDialect.test.ts).
  const canonical = htmlToJsx(ex.html);
  const roundTrips = jsxEquivalent(canonical, ex.jsx);
  const generated = htmlToJsx(ex.html, undefined, { dialect });
  const reingests = !ex.lossy && jsxToHtml(generated) === jsxToHtml(canonical);

  return {
    pass,
    roundTrips,
    node: (
      <section class="ex">
        <h2 class="ex-title">
          {ex.title}
          <span class={`badge ${pass ? 'pass' : 'fail'}`}>{pass ? '✓ conformant' : '✗ drift'}</span>
          {ex.lossy ? (
            <span class="badge info">lossy by design</span>
          ) : (
            <span class={`badge ${roundTrips ? 'pass' : 'fail'}`}>
              {roundTrips ? '✓ round-trips' : '✗ differs'}
            </span>
          )}
          {dialect === 'react' && !ex.lossy ? (
            <span class={`badge ${reingests ? 'pass' : 'fail'}`}>
              {reingests ? '✓ react ingests' : '✗ react differs'}
            </span>
          ) : null}
        </h2>
        {ex.note ? <p class="ex-note">{ex.note}</p> : null}
        <div class="ex-grid">
          <div class="pane">
            <div class="pane-label">JSX source (authored)</div>
            <pre class="code">{ex.jsx}</pre>
            <div class="pane-label" style="margin-top:0.75rem">
              Generated by htmlToJsx(HTML) · {dialect} dialect
            </div>
            <pre class="code gen">{generated}</pre>
          </div>
          <div class="pane">
            <div class="pane-label">Live render</div>
            <div class="preview">{live}</div>
          </div>
          <div class="pane">
            <div class="pane-label">Produced HTML {pass ? '= canonical' : '≠ canonical'}</div>
            <pre class="code">{html}</pre>
          </div>
        </div>
      </section>
    ),
  };
}

const host = document.getElementById('examples');

function renderAll(): number {
  if (!host) return 0;
  const built = examples.map(card);
  const passCount = built.filter((b) => b.pass).length;
  const roundTripCount = built.filter((b, i) => !examples[i].lossy && b.roundTrips).length;
  const reversible = examples.filter((e) => !e.lossy).length;
  const lossy = examples.length - reversible;
  const allPass = passCount === examples.length && roundTripCount === reversible;

  const toggle = (
    <div class="dialect-toggle" style="display:flex;gap:0.5rem;align-items:center;margin-bottom:0.75rem">
      <span class="pane-label">Authoring dialect (soft preference, #235):</span>
      {(['html', 'react'] as JsxDialect[]).map((d) => (
        <button
          type="button"
          class={`badge ${d === dialect ? 'pass' : 'info'}`}
          style="cursor:pointer;border:none"
          onClick={() => {
            if (d !== dialect) {
              dialect = d;
              renderAll();
            }
          }}
        >
          {d === 'html' ? 'html (class/for/onclick) · default' : 'react (className/htmlFor/onClick)'}
        </button>
      ))}
    </div>
  );

  const summary = (
    <div class={`summary ${allPass ? 'pass' : 'fail'}`}>
      Render: {passCount}/{examples.length} conformant (JSX→DOM = canonical) · Transform:{' '}
      {roundTripCount}/{reversible} round-trip (htmlToJsx → authored JSX){lossy ? `, ${lossy} lossy by design` : ''}
    </div>
  );
  host.replaceChildren(toggle, summary, ...built.map((b) => b.node));
  return passCount;
}

const passCount = renderAll();

// Activate any custom attributes the renderer produced (best-effort; bootstrap may expose `attributes`).
const we = window as unknown as { attributes?: { upgrade?: (root: Node) => void } };
we.attributes?.upgrade?.(document.body);

setPlaygroundReady(passCount);
